#cloud-config
package_upgrade: true
packages:
  - git-all
  - net-tools
  - ca-certificates
  - curl
  - gnupg
  - cmake
  - unzip
runcmd:
  - mkdir -p /run
  - cd /run
  - [ "sh" , "-c" , "git clone https://github.com/neovim/neovim"]
  - cd neovim
  - [ "sh" , "-c" , "git checkout stable"]
  - [ "sh" , "-c" , "make CMAKE_BUILD_TYPE=RelWithDebInfo"]
  - cd build
  - [ "sh" , "-c" , "cpack -G DEB"]
  - [ "sh" , "-c" , "dpkg -i nvim*.deb"]
